// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh-wFWxE_Sk2vnbyzW55Dmzo95mCd4WRw',
    appId: '1:1026849388042:web:ee78574713c6b149cb91f3',
    messagingSenderId: '1026849388042',
    projectId: 'talaa-5758a',
    authDomain: 'talaa-5758a.firebaseapp.com',
    storageBucket: 'talaa-5758a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzvV6wKW_oIoMup8x0EfKZELRDxMSvLDM',
    appId: '1:1026849388042:android:08b4de4ba18951becb91f3',
    messagingSenderId: '1026849388042',
    projectId: 'talaa-5758a',
    storageBucket: 'talaa-5758a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQu2MAn7ilMSP_VEoW1f6aIQcUqZvEzs',
    appId: '1:1026849388042:ios:a032b8de723f9468cb91f3',
    messagingSenderId: '1026849388042',
    projectId: 'talaa-5758a',
    storageBucket: 'talaa-5758a.firebasestorage.app',
    iosBundleId: 'com.example.talaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBQu2MAn7ilMSP_VEoW1f6aIQcUqZvEzs',
    appId: '1:1026849388042:ios:a032b8de723f9468cb91f3',
    messagingSenderId: '1026849388042',
    projectId: 'talaa-5758a',
    storageBucket: 'talaa-5758a.firebasestorage.app',
    iosBundleId: 'com.example.talaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh-wFWxE_Sk2vnbyzW55Dmzo95mCd4WRw',
    appId: '1:1026849388042:web:70c0ecbbfb35d95dcb91f3',
    messagingSenderId: '1026849388042',
    projectId: 'talaa-5758a',
    authDomain: 'talaa-5758a.firebaseapp.com',
    storageBucket: 'talaa-5758a.firebasestorage.app',
  );
}
